
 export const ele = {
    singUpBtn : document.querySelector("#singUP"),
    emailSP : document.querySelector(".emailSP"),
    name : document.querySelector(".name"),
    psw : document.querySelector(".psw"),
    sirName : document.querySelector(".sir-name"),
    day : document.querySelector("#day"),
    month : document.querySelector("#month"),
    year : document.querySelector("#year"),
    pswLogin : document.querySelector("#pswLogin"),
    newAccount : document.getElementById("new-account"),
    pageBg : document.querySelector(".flexCont"),
    singUpPage : document.querySelector(".singUp-sub"),
    crossBtn1 : document.getElementById('crossBtn'),
    emailLogin: document.getElementById("emailLogin"),
    pswLogin : document.getElementById("pswLogin"),
    inputFile: document.querySelector("#input-file"),
    personImg : document.querySelector("#person-img"),
    userName : document.querySelector("#user-name"),
    askText : document.querySelector("#thinksTwo"),
    crossBtn2 : document.querySelector("#crossBTN2"),
    askText : document.querySelector("#thinks"),
    askTextBox : document.querySelector(".thinks-Cont"),
    askTextBoxBg : document.querySelector(".felxContent"),
    crossBtn3 : document.querySelector("#crossBTN"),
    addPostBtn : document.querySelector("#add-post--btn"),
    askTextUserText : document.querySelector("#thinkText--text"),
    postBox : document.getElementById("postBox"),
    likeBtn : document.querySelectorAll(".like-btn"),
    filled : document.querySelectorAll(".like-fill"),
    outline : document.querySelectorAll(".like-outline"),
    postImgBtn : document.querySelector("#add-post--btnImg")
 
 }